feat: find crypto
defi-wonderland/check-crypto-action pull request #10
Opened 2022-10-04 17:35 UTC by turtlemoji

2022-10-04 19:44 UTC, 0xOneTony reviewed
lgtm 🌟🚀!  left a couple of comments open for discussion

2022-10-04 19:44 UTC, 0xOneTony commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') ?? false;
I believe it should be a string `'false'`, right?

2022-10-04 19:44 UTC, 0xOneTony commented on src/main.ts
> +    // if (inputs.output) {
I believe that showing the summary is enough, what do you think? If so, should we remove these comments? I noticed them on various files aswell.

2022-10-04 19:44 UTC, 0xOneTony commented on src/notifications.ts
> +    body: `## ${getTitle(label)}: ${result.passed ? 'Success' : 'Failure'}
From my understanding from `main.ts` `result.passed` is always gonna be false, right?

2022-10-04 19:44 UTC, 0xOneTony commented on .github/workflows/test.yml
> +      - uses: ./
I believe it's cleaner if we have a small description for each step e.g.

```
 steps:
      -name: Checkout sources
       uses: actions/checkout@v3
       
      -name: Search for secret
       uses: ./
       with: 
         ...
```

2022-10-04 19:49 UTC, turtlemoji commented on src/notifications.ts
> +    body: `## ${getTitle(label)}: ${result.passed ? 'Success' : 'Failure'}
No, it can pass, check the tests :
`  const passed = Object.keys(foundPrivates).length == 0;` 

![image](https://user-images.githubusercontent.com/78362532/193912226-bf7cab85-9c1f-4135-ab0f-fd4c42b41e25.png)

2022-10-04 19:50 UTC, turtlemoji commented on .github/workflows/test.yml
> +      - uses: ./
true

It is just used like this on the templates but I can change it, I like it more that way

2022-10-04 19:51 UTC, turtlemoji commented on src/main.ts
> +    // if (inputs.output) {
Yeah I just leave them because maybe `we will use them later`. 
I can remove the commends

2022-10-04 19:56 UTC, turtlemoji commented on .github/workflows/test.yml
> +      - uses: ./
fixed on 0486b21197fbbdbdc6d66fc6fc78c97f7c5c7aa5

2022-10-04 19:57 UTC, turtlemoji commented on src/main.ts
> +    // if (inputs.output) {
removed comment on 0486b21197fbbdbdc6d66fc6fc78c97f7c5c7aa5

2022-10-04 20:02 UTC, 0xOneTony commented on src/notifications.ts
> +    body: `## ${getTitle(label)}: ${result.passed ? 'Success' : 'Failure'}
> No, it can pass, check the tests : ` const passed = Object.keys(foundPrivates).length == 0;`
> 
I am referring specifically to this function, `createComment`. If you check on main.ts `result.passed` is always gonna be false when passed to `createComment`, so the check you are doing to print "Success" or "Failure" is always going to print on "Failure". Like your `if` says, it's posting if it fails.

https://github.com/defi-wonderland/check-crypto-action/blob/71a68bbc9789465f8bf5034f6c4deb22e2b9240e/src/main.ts#L24-L28

2022-10-04 20:05 UTC, turtlemoji commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') ?? false;
mmmm yeah it was using two types, messy, I will switch to boolean as it should good catch

2022-10-04 20:06 UTC, turtlemoji commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') ?? false;
fixed on d2ea917bb874fb28e50ffe1c95e97eb7a3bb00b5

2022-10-04 20:15 UTC, turtlemoji commented on src/notifications.ts
> +    body: `## ${getTitle(label)}: ${result.passed ? 'Success' : 'Failure'}
Oh, yes. In last iteration it was commenting on success too. I disabled it until we decide but probably we should create another input/flag like `notify_on_success`.

2022-10-04 20:20 UTC, 0xOneTony commented on src/notifications.ts
> +    body: `## ${getTitle(label)}: ${result.passed ? 'Success' : 'Failure'}
I think that commenting something like that on an issue is unnecessary, the action passing is enough imo. Commenting only on failure is fine

2022-10-04 20:23 UTC, 0xOneTony approved these changes
@0xGorilla lgtm!

2022-10-05 17:08 UTC, 0xGorilla commented on package.json
> +  "name": "check-crypto-action",
rename to "@defi-wonderland/crypto-pk-alert-action"

2022-10-05 17:09 UTC, 0xGorilla commented on package.json
>      "build": "tsc",
rename format and format-check to lint:fix and lint. both here and in the workflows

2022-10-05 17:13 UTC, 0xGorilla commented on package.json
>      "build": "tsc",
script all should use yarn and not npm

2022-10-05 17:13 UTC, 0xGorilla commented on package.json
> +    "url": "git+https://github.com/defi-wonderland/check-crypto-action.git"
rename repo to crypto-pk-alert-action

2022-10-05 17:13 UTC, 0xGorilla commented on package.json
>    "author": "",
"author": "Wonderland",

2022-10-05 17:14 UTC, 0xGorilla commented on package.json
> +    "@actions/core": "^1.6.0",
Use fixed versions everywhere

2022-10-05 17:14 UTC, 0xGorilla commented on package.json
>  {
no need for package-lock.json, where is the yarn.lock?

2022-10-05 17:15 UTC, 0xGorilla commented on package.json
> +  "version": "1.0.0",
change LICENSE file to have Wonderland's license (grab from any other repo, but it is a normal MIT)

2022-10-05 17:15 UTC, 0xGorilla commented on action.yml
> +name: 'Check Crypto Action'
Crypto PK Alert Action

2022-10-05 17:16 UTC, 0xGorilla commented on __tests__/main.test.ts
> +// import * as process from 'process';
wtf is this file haha

2022-10-05 17:17 UTC, 0xGorilla commented on src/main.ts
> +  } catch (e) {
Can't u just do `} catch (e: Error) {`?

2022-10-05 17:18 UTC, 0xGorilla commented on src/main.ts
> +    core.debug(`Calculate result`);
Calculating result

2022-10-05 17:20 UTC, 0xGorilla commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') === 'true';
Is this always a string? you sure about === 'true'?

2022-10-05 17:22 UTC, 0xGorilla commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') === 'true';
u have some constants with snake case and some other ones with camelCase

2022-10-05 17:23 UTC, 0xGorilla commented on src/inputs.ts
> +type GetInput = (name: string, options?: InputOptions | undefined) => string;
Shouldn't this go inside `namespaces` dir?

2022-10-05 17:24 UTC, 0xGorilla commented on src/processing.ts
> +  // NOTE Split diff line by line
Why do you add the prefix NOTE to comments?

2022-10-05 17:26 UTC, 0xGorilla commented on src/processing.ts
> +function searchForKey(keysArray: string[], foundKeysMap: AddressObject, currentFile: string): AddressObject {
This functions should be pure, thus, it shouldn't modify foundKeysMap. If you find an easy and tidy way to make it pure please do, if not, don't worry

2022-10-05 17:27 UTC, 0xGorilla commented on src/processing.ts
> +const getSummary = (passed: boolean, foundAddresses: AddressObject, foundPrivates: AddressObject): string => {
use function instead of const, and declare it under the external functions

2022-10-05 17:28 UTC, 0xGorilla commented on src/processing.ts
> +      const privateKeysFound = [...line.matchAll(/[1234567890abcdefABCDEF]{64}/g)].flat();
Wouldn't it be safer to check if it is a valid private key using ethers or something? Same for public keys

2022-10-05 17:31 UTC, 0xGorilla commented on __tests__/main.test.ts
> +// import * as process from 'process';
There are no tests that you consider necessary?

2022-10-05 17:35 UTC, 0xGorilla requested changes
Domo elegantooo

Very organised and clean code! A pleasure to read it.

Having no tests at all is a bit nasty tho

2022-10-05 19:07 UTC, turtlemoji commented on package.json
> +  "name": "check-crypto-action",
name shouldn't have the org, will put only `crypto-pk-alert-action`

2022-10-05 19:08 UTC, turtlemoji commented on package.json
> +  "name": "check-crypto-action",
not an alert tho. I would not put alert on it when is a build action

2022-10-05 19:38 UTC, turtlemoji commented on package.json
>      "build": "tsc",
I don't think so, since we are using prettier for format and not linting, lint is 100% better on eslint.
Check checkout action practice:
https://github.com/actions/checkout/blob/main/package.json

Yarn is not default installed on gh runners so I think thats why the all use npm
https://github.com/actions/checkout/blob/main/package-lock.json

npm works same as yarn from long ago (speed and etc) so I don't think we will have any problems

2022-10-05 19:42 UTC, turtlemoji commented on __tests__/main.test.ts
> +// import * as process from 'process';
We should for sure add tests.
I just leave the file for placeholder and a TODO, didn't have the time to do them yet.

2022-10-05 19:43 UTC, turtlemoji commented on src/main.ts
> +  } catch (e) {
You can't specify a type on the catch. Check:
`Catch clause variable type annotation must be 'any' or 'unknown' if specified.`

2022-10-05 19:44 UTC, turtlemoji commented on src/inputs.ts
> +  const onlyNotify = getInput('only_notify') === 'true';
It should always be an string or just false.
Practice accorss actons is to use slither on yml.

2022-10-05 20:46 UTC, turtlemoji commented on src/processing.ts
> +  // NOTE Split diff line by line
Just to give a context of what the comment is. 
// TODO
// NOTE
// PLACEHOLDER
// BUG
// FIX
only // == Ugly

2022-10-05 21:05 UTC, turtlemoji commented on src/processing.ts
> +      const privateKeysFound = [...line.matchAll(/[1234567890abcdefABCDEF]{64}/g)].flat();
Ethers end up using:
https://github.com/paulmillr/noble-secp256k1/blob/bb27483a1dbf46738928bacb9044dd62f6bf16c7/index.ts#L1484

So basically:
```typescript
function normalizePrivateKey(key: PrivKey): bigint {
  let num: bigint;
  if (typeof key === 'bigint') {
    num = key;
  } else if (typeof key === 'number' && Number.isSafeInteger(key) && key > 0) {
    num = BigInt(key);
  } else if (typeof key === 'string') {
    if (key.length !== 64) throw new Error('Expected 32 bytes of private key');
    num = hexToNumber(key);
  } else if (key instanceof Uint8Array) {
    if (key.length !== 32) throw new Error('Expected 32 bytes of private key');
    num = bytesToNumber(key);
  } else {
    throw new TypeError('Expected valid private key');
  }
  if (!isWithinCurveOrder(num)) throw new Error('Expected private key: 0 < key < n');
  return num;
}
```

So basically they end up checking 
`if (typeof key === 'string')  if (key.length !== 64)` and `if (!isWithinCurveOrder(num))`

we are doing the two checks with `[1234567890abcdefABCDEF]{64}`

2022-10-05 21:09 UTC, turtlemoji commented on package.json
> +  "name": "check-crypto-action",
idk about these let me know

2022-10-06 05:03 UTC, turtlemoji commented on src/inputs.ts
> +  let notifications;
0544754aeb65b344abca76bf8b5b4d28f139f681

2022-10-06 15:48 UTC, 0xGorilla commented on src/main.ts
> +  } catch (e) {
use:
```
const message = (e as Error).message ?? error;
core.debug(`Error: ${message}`);
core.setFailed(message);
```

2022-10-06 15:49 UTC, 0xGorilla commented on src/inputs.ts
> +  let notifications;
No need

2022-10-06 16:32 UTC, turtlemoji commented on src/main.ts
> +  } catch (e) {
dbef936a9eb07e8bce5b1e738eba9578197471ec

2022-10-06 18:07 UTC, turtlemoji commented on src/processing.ts
> +function searchForKey(keysArray: string[], foundKeysMap: AddressObject, currentFile: string): AddressObject {
6166aa65ea1c19cc93b415a339a078b9d8549b01

2022-10-10 20:46 UTC, turtlemoji commented on __tests__/main.test.ts
> +// import * as process from 'process';
9df75bc727eec226e37c108e06a167ce77f0cfed

2022-11-04 15:19 UTC, 0xGorilla commented on package.json
> +    "@vercel/ncc": "0.31.1",
vola

2022-11-04 15:22 UTC, 0xGorilla approved these changes

2022-11-06 18:46 UTC, 0xGorilla commented on README.md
> +| branch       | Name of branch to compare                                                       | **Required** |
Put the required first

2022-11-06 18:46 UTC, 0xGorilla commented on README.md
> +| notify_issue | Send a notification to the linked issue/pullrequest with the summary            | true         |
issue/pull-request

2022-11-06 18:47 UTC, 0xGorilla commented on README.md
> +You will need to supply a `token` to be able to send issue notifications
In order to send issue notifications on Github, you must supply the `token` input

2022-11-06 18:48 UTC, 0xGorilla commented on README.md
> +npm run build && npm run package
not yarn?

2022-11-06 18:53 UTC, turtlemoji commented on README.md
> +npm run build && npm run package
I will not encourage it for this, since that runners and etc sometimes doesn't have yarn, or are incompatible (like with set-scripts command) and etc.

2022-11-06 19:01 UTC, 0xGorilla approved these changes

2022-11-06 19:03 UTC, merged